### ISSUE TITLE
Proyecto Final Sistema para reservaciones de Hotel

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/proyecto-final-super_team#2]
[Proyecto final__Reservaciones de Hotel.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-super_team/files/6770951/Proyecto.final__Reservaciones.de.Hotel.pdf)

**Comment by javiern-778** [comment]
excelente trabajo: 80 puntos
califico : Javier Noe Cruz España

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
